version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "32714:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  airflow-webserver:
    build: ./airflow
    container_name: airflow_webserver
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "H9dZrsyHcCn0qR1THt1C9X6tMC-wK9C2w8h6dyYzEEc="
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ../dags:/opt/airflow/dags
      - ../logs:/opt/airflow/logs
      - ../plugins:/opt/airflow/plugins
      - ../data:/opt/airflow/data
    ports:
      - "43921:8080"
    command: webserver  
  airflow-init:
    build: ./airflow
    container_name: airflow_init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "H9dZrsyHcCn0qR1THt1C9X6tMC-wK9C2w8h6dyYzEEc="
    entrypoint: >
      bash -c "airflow db migrate &&
               airflow users create --username abner.lima --password admin --firstname Abner --lastname Lima --role Admin --email dev.abnerlima@gmail.com || true"
    volumes:
      - ../dags:/opt/airflow/dags
      - ../logs:/opt/airflow/logs
      - ../plugins:/opt/airflow/plugins
      - ../data:/opt/airflow/data
  airflow-scheduler:
    build: ./airflow
    container_name: airflow_scheduler
    depends_on:
      - postgres
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ../dags:/opt/airflow/dags
      - ../logs:/opt/airflow/logs
      - ../plugins:/opt/airflow/plugins
      - ../data:/opt/airflow/data
    command: scheduler  

volumes:
  postgres_data:
